AWSTemplateFormatVersion: "2010-09-09"
Description:
  rds for simplewebapp
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "all resource name next prefix"
        Parameters:
          - EnvironmentName
      - Label:
          default: "RDS Configuration"
        Parameters:
          - ClientKeyName
          - DBInstanceName
          - MySQLMajorVersion
          - MySQLMinorVersion
          - DBInstanceClass
          - DBInstanceStorageSize
          - DBInstanceStorageType
          - DBName
          - DBMasterUserName
          - DBPassword
          - MultiAZ
          - ClientInstansType
          - ClientImageId
    ParameterLabels:
      ClientKeyName:
        default: "ClientKeyName"
      DBInstanceName:
        default: "DBInstanceName"
      MySQLMajorVersion:
        default: "MySQLMajorVersion"
      MySQLMinorVersion:
        default: "MySQLMinorVersion"
      DBInstanceClass:
        default: "DBInstanceClass"
      DBInstanceStorageSize:
        default: "DBInstanceStorageSize"
      DBInstanceStorageType:
        default: "DBInstanceStorageType"
      DBName:
        default: "DBName"
      DBMasterUserName:
        default: "DBUserName"
      DBPassword:
        default: "DBPassword"
      MultiAZ:
        default: "MultiAZ"
      ClientInstansType:
        default: "ClientInstansType"
      ClientImageId:
        default: "ClientImageId"
# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  EnvironmentName:
    Type: String
  ClientKeyName:
    Type: AWS::EC2::KeyPair::KeyName
  DBInstanceName:
    Type: String
    Default: "rds"
  MySQLMajorVersion:
    Type: String
    Default: "8.0"
    AllowedValues: [ "8.0", "5.7" ]
  MySQLMinorVersion:
    Type: String
    Default: "34"
    AllowedValues: [ "34", "43" ]
  DBInstanceClass:
    Type: String
    Default: "db.t4g.micro" 
    AllowedValues: ["db.t4g.micro" ,"db.t3.micro","db.t2.micro"] 
  DBInstanceStorageSize:
    Type: String
    Default: "20"
  DBInstanceStorageType:
    Type: String
    Default: "gp2"
  DBName:
    Type: String
    Default: "SAMPLEDB"
  DBMasterUserName:
    Type: String
    Default: "mysqlUser"
    NoEcho: true
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "must begin with a letter and contain only alphanumeric characters."
  DBPassword: 
    Default: "Passw0rd"
    NoEcho: true
    Type: String
    MinLength: 8
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: "must contain only alphanumeric characters."
  MultiAZ: 
    Default: "false"
    Type: String
    AllowedValues: [ "true", "false" ]
  ClientInstansType:
    Type: String
    Default: "t2.micro"
  ClientImageId:
    Type: String
    Default: "ami-079cd5448deeace01"
  
Resources: 
# ------------------------------------------------------------#
#  DBInstance MySQL
# ------------------------------------------------------------#
  DBInstance: 
    Type: "AWS::RDS::DBInstance"
    Properties: 
      DBInstanceIdentifier: !Sub "${EnvironmentName}-${DBInstanceName}"
      Engine: MySQL
      EngineVersion: !Sub "${MySQLMajorVersion}.${MySQLMinorVersion}"
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBInstanceStorageSize
      StorageType: !Ref DBInstanceStorageType
      DBName: !Ref DBName
      MasterUsername: !Ref DBMasterUserName
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      MultiAZ: !Ref MultiAZ
      PreferredBackupWindow: "18:00-18:30"
      PreferredMaintenanceWindow: "sat:19:00-sat:19:30"
      AutoMinorVersionUpgrade: false
      DBParameterGroupName: !Ref DBParameterGroup  
      VPCSecurityGroups:
        - !ImportValue  SecurityGroupBackRds-ID
      CopyTagsToSnapshot: true
      BackupRetentionPeriod: 7
      Tags: 
        - Key: "Name"
          Value: !Ref DBInstanceName
    DeletionPolicy: "Delete"
  DBClient:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref ClientImageId
      SubnetId: !ImportValue PublicSubnet1-ID
      InstanceType: !Ref ClientInstansType
      KeyName: !Ref ClientKeyName
      SecurityGroupIds:
        - !ImportValue SecurityGroupDBClient-ID
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo dnf update -y
          sudo dnf install -y mariadb105
          echo -e "use SAMPLEDB;\nCREATE TABLE certtb(skillType varchar(255) , certName varchar(255));\nSHOW TABLES;" > /home/ec2-user/QueryData
          echo -e "#!/bin/bash\nmysql -h ${DBInstance.Endpoint.Address} -P 3306 -u ${DBMasterUserName} -p < QueryData" > /home/ec2-user/setupDB.sh 
      Tags:
        - Key: Name
          Value: RdsClient
# ------------------------------------------------------------#
#  DBParameterGroup
# ------------------------------------------------------------#
  DBParameterGroup:
    Type: "AWS::RDS::DBParameterGroup"
    Properties:
      Family: !Sub "MySQL${MySQLMajorVersion}"
      Description: !Sub "${EnvironmentName}-${DBInstanceName}-parm"

# ------------------------------------------------------------#
#  DBSubnetGroup
# ------------------------------------------------------------#
  DBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupName: !Sub "${EnvironmentName}-${DBInstanceName}-subnet"
      DBSubnetGroupDescription: "-"
      SubnetIds: 
        - !ImportValue PvSubnet1-ID
        - !ImportValue PvSubnet2-ID

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#                
Outputs:
  DBInstanceEndpoint:
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: "DBInstance-endpoint"
