# name: Docker

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   prebuild:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Go
#       uses: actions/setup-go@v4
#       with:
#         go-version: '1.21.2'
#     - name: Test
#       run: go test -v ./Go/...    
#   build:
#     runs-on: ubuntu-latest
#     needs: prebuild
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v4
#       - name: Log in to Docker Hub
#         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
#         with:
#           images: haruapp/gopersonalcolor
#       - name: Build 
#         env: 
#           tags: ${{ steps.meta.outputs.tags }}
#         run: docker compose -f ./Go/compose.yaml build && export IMAGENAME=`docker image ls | head -n 2  | tail -n 1 | awk '{print $1}'` && docker tag $IMAGENAME $tags && docker push $tags
#       #   tag: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
